Bonus_Board_app/urls.py
from django.conf.urls import url, include
from django.contrib import admin

from django.views.generic import TemplateView

from bonus_records import urls as record_urls
from users import urls as user_urls
from companies import urls as group_urls

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^users/', include(user_urls, namespace='users')),
    url(r'^bonus_records/', include(record_urls, namespace='records')),
    url(r'^companies/', include(group_urls, namespace='groups')),
    url(r'^$', TemplateView.as_view(template_name='index.html'), name='home'),
]

bonus_records/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^create/$', views.CreateRecord.as_view(), name='create'),
    url(r'^delete/(?P<pk>\d+)/$', views.DeleteRecordView.as_view(), name='record_delete'),
]

users/urls.py
from django.conf.urls import url, include

from . import views

urlpatterns = [
    url(r'^dashboard/$', views.Dashboard.as_view(), name='dashboard'),
    url(r'^logout/$', views.LogoutView.as_view(), name='logout'),
    url(r'^signup/$', views.SignUpView.as_view(), name='signup'),
    url('^', include('django.contrib.auth.urls')),
]

bonus_records/models.py
from django.contrib.auth.models import User
from django.db import models
from django.utils import timezone
from companies.models import Company
from . validators import company_user_validation


class Record(models.Model):
    company = models.ForeignKey(Company, related_name='bonus_records', null=True, blank=False, validators=[company_user_validation])
    user = models.ForeignKey(User, related_name='bonus_records', null=True, blank=False)
    recorded_at = models.DateTimeField(default=timezone.now, editable=False)
    amount = models.IntegerField()
    notes = models.TextField(blank=True, default='')

    def __str__(self):
        return '{}: £{}: {}'.format(self.recorded_at.strftime('%Y-%M-%D'), self.amount, self.notes)

    class Meta:
        ordering = ['-recorded_at']

bonus_records/forms.py
from django import forms

from . import models


class RecordForm(forms.ModelForm):
    class Meta:
        fields = ('amount', 'notes', 'company')
        model = models.Record

    def __init__(self, *args, **kwargs):
        user = kwargs.pop("user", None)
        super().__init__(*args, **kwargs)
        if user is not None:
            self.fields["company"].queryset = (
                models.Company.objects.filter(
                    pk__in=user.companies.values_list("company__pk")
                )
            )


class DeleteForm(forms.ModelForm):
    pass

bonus_records/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.core.urlresolvers import reverse_lazy
from django.views.generic import CreateView, DeleteView

from braces.views import SelectRelatedMixin

from .forms import RecordForm
from . models import Record


class CreateRecord(LoginRequiredMixin, SelectRelatedMixin, CreateView):
    form_class = RecordForm
    select_related = ('user', 'company')
    success_url = reverse_lazy('users:dashboard')

    def form_valid(self, form):
        form.instance.user = self.request.user
        return super().form_valid(form)


class DeleteRecordView(LoginRequiredMixin, DeleteView):
    model = Record
    success_url = reverse_lazy('users:dashboard')

    def get_queryset(self):
        user_id = self.request.user
        return self.model.objects.filter(user_id=user_id)

bonus_records/templates/records/_confirm_delete.html
{% extends "layout.html" %}

{% block header %}{% endblock header %}

{% block content %}
<div>
     <div class="alert alert-danger" role="alert">
          <p>Are you sure you want to delete the contact {{ record }}?</p>

          <form action="{% url 'record-delete' pk=record.id %}" method="POST">
               {% csrf_token %}

               <input type="submit" value="Yes, delete." />
               <a href="{% url 'users:dashboard' %}">No, cancel.</a>
          </form>
     </div>
</div>
{% endblock %}

bonus_records/templates/records/_form.html
{% load bootstrap4 %}

<form method="POST" action="{% url 'records:create' %}">
    <h3>How much did you earn?</h3>
    {% csrf_token %}
    <div class="row">
        {% bootstrap_form form %}
    </div>
    {% buttons %}
    <input type="submit" value="Record" class=" btn btn-success">
    {% endbuttons %}
</form>