Bonus_Board_app/urls.py
from django.conf.urls import url, include
from django.contrib import admin

from django.views.generic import TemplateView

from bonus_records import urls as record_urls
from users import urls as user_urls
from companies import urls as group_urls

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^users/', include(user_urls, namespace='users')),
    url(r'^bonus_records/', include(record_urls, namespace='records')),
    url(r'^companies/', include(group_urls, namespace='groups')),
    url(r'^$', TemplateView.as_view(template_name='index.html'), name='home'),
]

bonus_records/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^create/$', views.CreateRecord.as_view(), name='create'),
    url(r'^delete/(?P<pk>\d+)/$', views.DeleteRecordView.as_view(), name='record_delete'),
]

users/urls.py
from django.conf.urls import url, include

from . import views

urlpatterns = [
    url(r'^dashboard/$', views.Dashboard.as_view(), name='dashboard'),
    url(r'^logout/$', views.LogoutView.as_view(), name='logout'),
    url(r'^signup/$', views.SignUpView.as_view(), name='signup'),
    url('^', include('django.contrib.auth.urls')),
]

bonus_records/models.py
from django.contrib.auth.models import User
from django.db import models
from django.utils import timezone
from companies.models import Company
from . validators import company_user_validation


class Record(models.Model):
    company = models.ForeignKey(Company, related_name='bonus_records', null=True, blank=False, validators=[company_user_validation])
    user = models.ForeignKey(User, related_name='bonus_records', null=True, blank=False)
    recorded_at = models.DateTimeField(default=timezone.now, editable=False)
    amount = models.IntegerField()
    notes = models.TextField(blank=True, default='')

    def __str__(self):
        return '{}: £{}: {}'.format(self.recorded_at.strftime('%Y-%M-%D'), self.amount, self.notes)

    class Meta:
        ordering = ['-recorded_at']

users/forms.py
from django import forms


class LogoutForm(forms.Form):
    pass

users/views.py
from django.contrib.auth import logout
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django.contrib.auth.mixins import LoginRequiredMixin
from django.core.urlresolvers import reverse, reverse_lazy
from django.http import HttpResponseRedirect
from django.views import generic

from braces.views import SelectRelatedMixin

from . import forms


class Dashboard(LoginRequiredMixin,
                SelectRelatedMixin,
                generic.DetailView
                ):
    model = User
    select_related = ('records',)
    template_name = 'users/dashboard.html'

    def get_object(self, queryset=None):
        return self.request.user


class LogoutView(LoginRequiredMixin, generic.FormView):
    form_class = forms.LogoutForm
    template_name = 'users/logout.html'

    def form_valid(self, form):
        logout(self.request)
        return HttpResponseRedirect(reverse('home'))


class SignUpView(generic.CreateView):
    form_class = UserCreationForm
    template_name = 'users/signup.html'
    success_url = reverse_lazy('users:dashboard')

users/templates/users/dashboard.html
{% extends 'layout.html' %}
{% load static from staticfiles %}

{% load record_tags %}

{% block title %}Dashboard | {{ block.super }}{% endblock %}

{% block content %}
{% if user.is_staff or user.is_superuser %}
<div class="container pt">
    <div class="row">
        <div class="col-md-6">
            <h3>Recent Logs</h3>
            <div class="list-group">
                {% for record in user.bonus_records.all|slice:":1" %}
                <a href="#" class="list-group-item list-group-item-action flex-column align-items-start">
                <div class="d-flex w-100 justify-content-between">
                    <h5 class="mb-1">€{{ record.amount }}</h5>
                    <small class="text-muted">{{ record.recorded_at|date:'SHORT_DATE_FORMAT' }}</small>
                </div>
                    {% if record.notes %}
                    <p class="text-muted">{{ record.notes|linebreaks }}</p>
                    {% endif %}
                </a>
                {% if record.id %}
                <form action="{% url 'records:record_delete' pk=record.id %}" method="POST">
                    {% csrf_token %}
                    <button type="submit" value="Delete" class="btn btn-danger btn-lg btn-block">Delete</button>
                </form>
                {% endif %}
                {% endfor %}
            </div>
        </div>
        <div class="col-md-4">
            {% record_form %}
        </div>
    </div>
    <div class="row">
        <div class="col-md-6">
            <div class="ct-chart ct-perfect-fourth"></div>
        </div>
        {% else %}
        <div class="container pt">
            <div class="col-md-12">
                <div class="alert alert-success" role="alert">
                    <h4 class="alert-heading">Welcome!</h4>
                    <p>Aww yeah, you successfully read this important alert message. This example text is going to run a bit longer so that you can see how spacing within an alert works with this kind of content.</p>
                    <p class="mb-0">Whenever you need to, be sure to use margin utilities to keep things nice and tidy.</p>
                </div>
            </div>
        </div>
    </div>
</div>
{% endif %}
{% endblock %}

{% block css %}
    <link rel="stylesheet" href="{% static 'js/chartist/chartist.min.css' %}">
{% endblock %}

{% block js %}
    <script src="{% static 'js/stretchy.js' %}" data-filter="#id_notes"async></script>
    <script src="{% static 'js/chartist/chartist.min.js' %}"></script>
    <script>
        {% chart_data as data %}
        var data = {{ data|safe }};
        new Chartist.Line('.ct-chart', data);
    </script>
{% endblock %}

users/templates/users/logout.html
{% extends 'layout.html' %}
{% load bootstrap4 %}

{% block title %}Logout | {{ block.super }}{% endblock %}

{% block content %}
<div class="container pt">
    <div class="row">
        <div class="col-md-6">
            <h3>You sure you want to logout?</h3>
            <form method="POST">
                {% bootstrap_form form %}
                {% csrf_token %}
                {% buttons %}
                <input type="submit" value="Logout" class="btn btn-danger">
                {% endbuttons %}
            </form>
        </div>
        <div class="col-md-6">
            <h3>Come back soon!</h3>
            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum</p>
        </div>
    </div>
</div>
{% endblock %}

users/templates/users/signup.html
{% extends 'layout.html' %}
{% load bootstrap4 %}

{% block title %}Sign Up | {{ block.super }}{% endblock %}

{% block content %}
<div class="container pt">
    <div class="row">
        <div class="col-md-6">
            <h3>Sign Up</h3>
            <form method="POST">
                {% bootstrap_form form %}
                {% csrf_token %}
                {% buttons %}
                <input type="submit" value="Sing Up" class="btn btn-success">
                {% endbuttons %}
            </form>
        </div>
        <div class="col-md-6">
            <h3>Log and record your cash!</h3>
            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum</p>
        </div>
    </div>
</div>
{% endblock %}