Bonus_Board_app/urls.py
from django.conf.urls import url, include
from django.contrib import admin

from django.views.generic import TemplateView

from bonus_records import urls as record_urls
from users import urls as user_urls
from companies import urls as group_urls

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^users/', include(user_urls, namespace='users')),
    url(r'^bonus_records/', include(record_urls, namespace='records')),
    url(r'^companies/', include(group_urls, namespace='groups')),
    url(r'^$', TemplateView.as_view(template_name='index.html'), name='home'),
]

users/urls.py
from django.conf.urls import url, include

from . import views

urlpatterns = [
    url(r'^dashboard/$', views.Dashboard.as_view(), name='dashboard'),
    url(r'^logout/$', views.LogoutView.as_view(), name='logout'),
    url(r'^signup/$', views.SignUpView.as_view(), name='signup'),
    url('^', include('django.contrib.auth.urls')),
]

templates/index.html
{% extends "layout.html" %}

{% block content %}
<!-- Main jumbotron for a primary marketing message or call to action -->
    <div class="jumbotron">
      <div class="container">
        <h1>Welcome too the profit sharing application!</h1>
        <p>This is a template for a simple marketing or informational website. It includes a large callout called a jumbotron and three supporting pieces of content. Use it as a starting point to create something more unique.</p>
        <p><a class="btn btn-primary btn-lg" href="#" role="button">Learn more &raquo;</a></p>
      </div>
    </div>
    <div class="container">
      <!-- Example row of columns -->
      <div class="row">
        <div class="col-md-4">
          <h2>Heading</h2>
          <p>Donec id elit non mi porta gravida at eget metus. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus. Etiam porta sem malesuada magna mollis euismod. Donec sed odio dui. </p>
          <p><a class="btn btn-outline-primary" href="#" role="button">View details &raquo;</a></p>
        </div>
        <div class="col-md-4">
          <h2>Heading</h2>
          <p>Donec id elit non mi porta gravida at eget metus. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus. Etiam porta sem malesuada magna mollis euismod. Donec sed odio dui. </p>
          <p><a class="btn btn-outline-primary" href="#" role="button">View details &raquo;</a></p>
       </div>
        <div class="col-md-4">
          <h2>Heading</h2>
          <p>Donec sed odio dui. Cras justo odio, dapibus ac facilisis in, egestas eget quam. Vestibulum id ligula porta felis euismod semper. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus.</p>
          <p><a class="btn btn-outline-primary" href="#" role="button">View details &raquo;</a></p>
        </div>
      </div>
    </div>
{% endblock %}

templates/layout.html
{% load static from staticfiles %}
<!doctype html>
<html lang="en">
  <head>
    <title>{% block title %}PiggyBank{% endblock %}</title>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/css/bootstrap.min.css" integrity="sha384-PsH8R72JQ3SOdhVi3uxftmaW6Vc51MKb0q5P2rRUpPvrszuE4W1povHYgTpBfshb" crossorigin="anonymous">
    <!-- Custom CSS -->
      {% block css %}{% endblock %}
    <link rel="stylesheet" href="{% static 'css/bonus_board_app.css' %}">
  </head>
  <body>
    <nav class="navbar navbar-expand-md navbar-dark fixed-top bg-dark">
      <a class="navbar-brand" href="{% url 'home' %}">Piggy Bank</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarsExampleDefault" aria-controls="navbarsExampleDefault" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
        {% if user.is_authenticated %}
        <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" data-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">Companies</a>
            <div class="dropdown-menu">
                <a class="dropdown-item" href="{% url 'groups:companies:invites' %}">Invitations</a>
                {% for company in user.companies.all %}
                <a class="dropdown-item" href="{% url 'groups:companies:detail' slug=company.slug %}">{{ company.name }}</a>
                {% endfor %}
                {% if user.is_staff or user.is_superuser %}
                <div role="separator" class="dropdown-divider"></div>
                <a class="dropdown-item" href="{% url 'groups:companies:create' %}">Create Company</a>
                {% endif %}
            </div>
        </li>
        {% endif %}
        <ul class="navbar-nav ml-auto">
              {% if not user.is_authenticated %}
              <li><a class="nav-link" href="{% url 'users:login' %}">Login</a></li>
              <li><a class="nav-link" href="{% url 'users:signup' %}">Sign up</a></li>
              {% else %}
              <li><a class="nav-link" href="{% url 'users:dashboard' %}">Dashboard</a></li>
              <li><a class="nav-link" href="{% url 'users:logout' %}">Logout</a></li>
              {% endif %}
          </ul>
    </nav>

    <div class="content">
      {% block content %}{% endblock %}
    </div>

    <div class="container">
        <hr>
        <footer>
        <p>&copy; 2017 PiggyBank, Inc.</p>
        </footer>
    </div>

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.3/umd/popper.min.js" integrity="sha384-vFJXuSJphROIrBnz7yo7oB41mKfc8JzQZiCq4NCceLEaO4IHwicKwpJf9c9IpFgh" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/js/bootstrap.min.js" integrity="sha384-alpBpkh1PFOepccYVYDB4do5UnbKysX5WZXm3XxPqe5iKTfUKjNkCk9SaVuEZflJ" crossorigin="anonymous"></script>
  {% block js %}{% endblock %}
  </body>
</html>